### ISSUE TITLE
How do we add `crypto-utils`?

### ISSUE THREAD

**Issue by arantespp** [asgardeo/asgardeo-auth-js-sdk#172]
**Is your suggestion related to a missing or misleading document? Please describe.**

Now that crypto-utils was removed, how are we supposed to add it when instantiating the class?

**Describe the improvement**

From [the constructor implementation](https://github.com/asgardeo/asgardeo-auth-js-sdk/blob/105954a651ff6308dd58c6df265a5b2d44886983/lib/src/authentication-client.ts#L78), we need to provide a `crypto-utils` module to `AsgardeoAuthClient`. How can I find the `crypto-utils` for React and React Native?

---

### Optional Fields

**Related Issues:**

https://github.com/asgardeo/asgardeo-auth-js-sdk/pull/167

**Comment by thivi** [comment]
Hi @arantespp,
We are actively working on version v1.0.0 of this SDK. Since there could be more changes, I recommend you to use v0.2.20 of the SDK. We will update the document when the changes are finalized. If you still want to work on the latest version, you can refer to this to implement crypto utils: https://github.com/asgardeo/asgardeo-react-native-oidc-sdk/blob/main/lib/src/crypto-utils.ts
